//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlInputs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Reason { get; set; }
        public System.DateTime DateOfMiss { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public int isRead { get; set; }
        public string Head { get; set; }
        public int isConfirmed { get; set; }
        public System.DateTime DateOfRead { get; set; }
        public string Reader { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
