//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlInputs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missings
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Form { get; set; }
        public int IsValid { get; set; }
        public int IsRead { get; set; }
        public System.DateTime Date { get; set; }
        public int Discipline { get; set; }
    
        public virtual Discipline Discipline1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
