//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlInputs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missings
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Form { get; set; }
        public string Discipline { get; set; }
        public int IsValid { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
