//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlInputs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility
    {
        public int Id { get; set; }
        public string Parameter { get; set; }
        public int Limit { get; set; }
    }
}
